### ISSUE TITLE
Proxy session establishment in v1 and v2

### ISSUE THREAD

**Issue by mpiraux** [obonaventure/draft-quic-atsss-reqs#37]
There is a fundamental change between ATSSS v1 and v2. In v1, using the TCP Converter protocol, sessions between the UE and the Proxy are established as new TCP flow are created. During the establishment of the Converter session, the use of MPTCP is limited as subflows are created later.
In v2, the QUIC session is created in advance, so this reduces the delay for Switching and Splitting.
Should we discuss that ?

**Comment by SpencerDawkins** [comment]
Maxime,

On Mon, May 11, 2020 at 3:37 AM Maxime Piraux <notifications@github.com>
wrote:

> There is a fundamental change between ATSSS v1 and v2. In v1, using the
> TCP Converter protocol, sessions between the UE and the Proxy are
> established as new TCP flow are created. During the establishment of the
> Converter session, the use of MPTCP is limited as subflows are created
> later.
> In v2, the QUIC session is created in advance, so this reduces the delay
> for Switching and Splitting.
>
Agreed so far.

> Should we discuss that ?
>
My suggestion would be that, in this draft, we limit ourselves to

   - Things that QUIC WG needs to know, in order to consider whether they
   can provide a needed capability in MP-QUIC, and (to a lesser extent)
   - Things that QUIC WG is going to worry about, that ATSSS does not need
   from MP-QUIC (like general distribution of policy, which is a big question,
   but 3GPP sidesteps with ATSSS rules).

ISTM that this fundamental change is worth noting - but not in a draft for
QUIC WG. Should we be working on a contribution for SA2 that says this? :-)

Best,

Spencer

**Comment by mpiraux** [comment]
Agreend, let's not discuss this in this document then.
