### ISSUE TITLE
Remove "Terms used in this document" section?

### ISSUE THREAD

**Issue by mirjak** [obonaventure/draft-quic-atsss-reqs#55]
I don't think we need the "Terms used in this document" section in an IETF internet-draft. However we might want to double-check if we want to add some more of these terms in the terminology section at the beginning.

**Comment by SpencerDawkins** [comment]
Hi, Mirja, 

I added the Terms used in this document early in the development of the draft, based on two concerns - we were bringing in a lot of 3GPP-specific terms that were not necessary to explain to IETF people what 3GPP needed from IETF protocols, and because we had multiple contributors, I was concerned that some terms would be used inconsistently, or that multiple terms might be used to describe the same thing. 

That section was based on pull requests up to about #17, so we definitely need to perform the same consistency pass over the entire 56-pull request document, but deleting this section before submission is the Right Thing To Do. 

Thanks!

**Comment by SpencerDawkins** [comment]
I added PR#74 with an updated list - we're getting closer to being able to update the Terminology section and delete Terms Used In This Document.
